Theme.find_or_create_by(color: "ff0066", wallpaper: "TestBackground.jpg")
Theme.find_or_create_by(color: "379cd3", wallpaper: "TestBackground2.jpg")
Theme.find_or_create_by(color: "038c0d", wallpaper: "TestBackground3.jpg")
Theme.find_or_create_by(color: "db2400", wallpaper: "TestBackground4.jpg")
Theme.find_or_create_by(color: "c254ad", wallpaper: "TestBackground5.jpg")
Theme.find_or_create_by(color: "00a78d", wallpaper: "TestBackground6.jpg")